### ISSUE TITLE
Allow to change service name when creating new Span

### ISSUE THREAD

**Issue by bharat-p** [uber/jaeger-client-python#46]
At present "service_name" is set during tracer initialization and service name set at tracer level is used as service_name when reporting a span.
It would be better if user can be allowed to change (override) "service_name" when creating a new span. 

Why?
It will allow developers to change service_name for spans created to track a remove server call.
E.g. While handling an API call from a service ( "api-service")  if we are making calls to external services like ElasticSearch or Mongo, new spans which are used to track these remote call can specify "service_name"="elasticsearch" or service_name="mongo" instead of using default service_name="api-service".

**Comment by yurishkuro** [comment]
the name of the remote server should be set on the span as `peer.service`. Typically each RPC call is represented by two spans, one in the calling service (span.kind=client), and the other in the called service (span.kind=server). The "service name" remains constant in each service and tells which service emitted which span.

**Comment by bharat-p** [comment]
Thanks for that explanation, "peer.service" is set as a tag on span? I am setting tag "peer.service" on my span, but I don't see this in Jaeger UI.

**Comment by yurishkuro** [comment]
Yes, it's one of the standard tags (there are constants for them in opentracing lib). You need to click on the span to expand its details to see the tags

![image](https://cloud.githubusercontent.com/assets/3523016/26177818/587333cc-3b29-11e7-8bc9-3c4af132d945.png)

**Comment by bharat-p** [comment]
Hmm, interesting I don't see in on my end. BTW, I am using `jaegertracing/all-in-one:latest` to log and view the traces. I did confirm that `peer` property on `span` object has correct values and trace JSON on Jaeger UI is also not showing any tag named `peer.service` any other custom tags I put from my app are showing there

**Comment by yurishkuro** [comment]
This could be a bug in the backend. The Python client currently uses `zipkin.thrift` format to emit spans, which is internally transformed to Jaeger data model, and because Zipkin represents peer service in a different way, the transformation from zipkin to Jaeger format should reconstruct the `peer.service` tag.

**Comment by yurishkuro** [comment]
Withdrawing my comment about the bug in the backend - I just checked a few of our internal services that use Go client, which also sends zipkin.thrift at this time, and they all show peer.service tags fine.

**Comment by bharat-p** [comment]
Thanks @yurishkuro  for checking and confirming that. I will do some additional debugging on my end.

**Comment by yurishkuro** [comment]
You may want to run a tcpdump on the UDP port and check what kind of strings are being included in thrift

**Comment by bharat-p** [comment]
So I did run 'tcpdump' and confirmed `peer.service` tag is not getting propagated. I confirmed by switching to zipkin based tracing ( using py_zipkin) that all tags I am setting including ( peer.*) are making their way to zipkin.

**Comment by black-adder** [comment]
It's probably this: https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/span.py#L195

It looks like we do special handling for some opentracing tags in python (ie. we remove them but set the zipkin equivalent on the zipkin endpoint). On the backend, we should be converting the zipkin endpoint service name back into the peer.service tag though. Since you're not seeing that occur, looks like a bug either in the backend when we do the conversion or the client when we send the zipkin thrift to the agent. I'll take a look.

**Comment by bharat-p** [comment]
Looks like based on comment on https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/span.py#L239 , this https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/span.py#L201 should be changed to False?

**Comment by bharat-p** [comment]
Let me try making above change and testing it again, if it works will submit a PR

**Comment by black-adder** [comment]
Given the way the backend zipkin to jaeger model conversion happens, we will be double reporting the same opentracing tags if we change it to False (granted the bug is fixed).

**Comment by bharat-p** [comment]
Ok, confirmed setting it to False does indeed make it work.
![screen shot 2017-05-23 at 11 04 23 am](https://cloud.githubusercontent.com/assets/13206972/26368845/b38a06f0-3fa7-11e7-992c-8dbd2fe69f7a.png)

**Comment by black-adder** [comment]
Are you setting the span.kind tag by any chance? If not can you try setting it?

**Comment by bharat-p** [comment]
No I am not, but I can try to set it.

**Comment by bharat-p** [comment]
Ok, if I set `span.kind` = `client` it does show up in Jaeger UI. So it seems you are right, setting False might not be the right fix and it must be an issue with Thrift conversion or somewhere else.

**Comment by black-adder** [comment]
https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/thrift.py#L149 If the span doesn't contain span.kind tag, we consider it a local component which according to opentracing semantics cannot have a peer service tag (because all the work occurs within the same service).

So you have to set the span.kind tag for all your incoming and outgoing spans for the peer.service tag to be set. I don't think there's a bug here.

**Comment by bharat-p** [comment]
Aah ok, thanks for clarifying that.
